create schema dogs_project;
create table dogs_project.users(
    username varchar(60) unique primary key not null ,
    password varchar(70) not null ,
    enabled  tinyint not null
);
create  table dogs_project.Dog(
    Id int primary key auto_increment,
    name varchar(70),
    image_link varchar(100),
    playfulness int,
    good_with_children int,
    good_with_other_dogs int,
    energy int
);

create table dogs_project.authorities(
    username varchar(60) not null ,
    authority varchar(60) not null,
    unique key authorities_idx_1 (username,authority),
    constraint authorities_ibfk_1
    foreign key (username) references users(username)
);
create table dogs_project.user_details(
    username varchar(60) not null,
    first_name varchar(60),
    last_name varchar(60),
    email varchar(80),
    country varchar(60),
    foreign key (username) references users(username)

);
-- bcrypt password fun123
INSERT INTO dogs_project.users(username, password,enabled) values ('jano','{bcrypt}$2a$10$NlXsSaheyHCT3pDd9XSWo.tkR0bNmyvDG9Hv2r7.vGozrRqZGUdlW',1);
INSERT INTO dogs_project.users(username, password,enabled) values ('dave','{bcrypt}$2a$10$NlXsSaheyHCT3pDd9XSWo.tkR0bNmyvDG9Hv2r7.vGozrRqZGUdlW',1);
INSERT INTO dogs_project.users(username, password,enabled) values ('jacob','{bcrypt}$2a$10$NlXsSaheyHCT3pDd9XSWo.tkR0bNmyvDG9Hv2r7.vGozrRqZGUdlW',1);
insert into dogs_project.Dog(name, image_link, playfulness, good_with_children, good_with_other_dogs, energy) values ("labrador retriever","https://api-ninjas.com/images/dogs/labrador_retriever.jpg",5,5,5,3);
insert into dogs_project.authorities(username, authority) VALUES ('jano','ROLE_MANAGER');
insert into dogs_project.authorities(username, authority) VALUES ('jano','ROLE_USER');
insert into dogs_project.authorities(username, authority) VALUES ('dave','ROLE_ADMIN');
insert into dogs_project.authorities(username, authority) VALUES ('dave','ROLE_MANAGER');
insert into dogs_project.authorities(username, authority) VALUES ('dave','ROLE_USER');
insert into dogs_project.authorities(username, authority) VALUES ('jacob','ROLE_USER');
insert into dogs_project.user_details(username, first_name, last_name, email, country) VALUES ('dave','Dawid','Tyrko','someEmail@gmail.com','Poland');
insert into dogs_project.user_details(username, first_name, last_name, email, country) VALUES ('jano','Janek','Kowalski','someEmail@gmail.com','Poland');
insert into dogs_project.user_details(username, first_name, last_name, email, country) VALUES ('jacob','Kuba','Stefanowicz','someEmail@gmail.com','Poland');

-- pod hsql --

CREATE TABLE users (
                       username VARCHAR(60) PRIMARY KEY NOT NULL,
                       password VARCHAR(70) NOT NULL,
                       enabled TINYINT NOT NULL
);

CREATE TABLE Dog (
                     Id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
                     name VARCHAR(70),
                     image_link VARCHAR(100),
                     playfulness INT,
                     good_with_children INT,
                     good_with_other_dogs INT,
                     energy INT
);

CREATE TABLE authorities (
                             username VARCHAR(60) NOT NULL,
                             authority VARCHAR(60) NOT NULL,
                             CONSTRAINT authorities_idx_1 UNIQUE (username, authority),
                             CONSTRAINT authorities_ibfk_1 FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE user_details (
                              username VARCHAR(60) NOT NULL,
                              first_name VARCHAR(60),
                              last_name VARCHAR(60),
                              email VARCHAR(80),
                              country VARCHAR(60),
                              FOREIGN KEY (username) REFERENCES users(username)
);


INSERT INTO users (username, password, enabled) VALUES ('jano', '{bcrypt}$2a$10$NlXsSaheyHCT3pDd9XSWo.tkR0bNmyvDG9Hv2r7.vGozrRqZGUdlW', 1);
INSERT INTO users (username, password, enabled) VALUES ('dave', '{bcrypt}$2a$10$NlXsSaheyHCT3pDd9XSWo.tkR0bNmyvDG9Hv2r7.vGozrRqZGUdlW', 1);
INSERT INTO users (username, password, enabled) VALUES ('jacob', '{bcrypt}$2a$10$NlXsSaheyHCT3pDd9XSWo.tkR0bNmyvDG9Hv2r7.vGozrRqZGUdlW', 1);

INSERT INTO Dog (name, image_link, playfulness, good_with_children, good_with_other_dogs, energy)
VALUES ('labrador retriever', 'https://api-ninjas.com/images/dogs/labrador_retriever.jpg', 5, 5, 5, 3);

INSERT INTO authorities (username, authority) VALUES ('jano', 'ROLE_MANAGER');
INSERT INTO authorities (username, authority) VALUES ('jano', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('dave', 'ROLE_ADMIN');
INSERT INTO authorities (username, authority) VALUES ('dave', 'ROLE_MANAGER');
INSERT INTO authorities (username, authority) VALUES ('dave', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('jacob', 'ROLE_USER');

INSERT INTO user_details (username, first_name, last_name, email, country)
VALUES ('dave', 'Dawid', 'Tyrko', 'someEmail@gmail.com', 'Poland');
INSERT INTO user_details (username, first_name, last_name, email, country)
VALUES ('jano', 'Janek', 'Kowalski', 'someEmail@gmail.com', 'Poland');
INSERT INTO user_details (username, first_name, last_name, email, country)
VALUES ('jacob', 'Kuba', 'Stefanowicz', 'someEmail@gmail.com', 'Poland');

-- koniec hsql --
